function Tomahawk(){}Tomahawk._classes=new Object;Tomahawk._extends=new Array;Tomahawk.registerClass=function(classDef,className){Tomahawk._classes[className]=classDef};Tomahawk.extend=function(p_child,p_ancestor){Tomahawk._extends.push({"child":p_child,"ancestor":p_ancestor})};Tomahawk.run=function(){var obj=null;var i=0;var max=Tomahawk._extends.length;for(i=0;i<max;i++)Tomahawk._inherits(Tomahawk._extends[i])};
Tomahawk._getParentClass=function(child){var i=0;var max=Tomahawk._extends.length;for(i=0;i<max;i++){obj=Tomahawk._extends[i];if(obj["child"]==child)return obj}return null};
Tomahawk._inherits=function(obj){var child=null;var ancestor=null;var superParent=Tomahawk._getParentClass(obj["ancestor"]);if(superParent!=null)Tomahawk._inherits(superParent);child=Tomahawk._classes[obj["child"]];ancestor=Tomahawk._classes[obj["ancestor"]];if(child!=null&&ancestor!=null){ancestor=new ancestor;for(var prop in ancestor)if(!child.prototype[prop])child.prototype[prop]=ancestor[prop]}};function AssetsLoader(){this._loadingList=new Array}Tomahawk.registerClass(AssetsLoader,"AssetsLoader");
AssetsLoader._instance=null;AssetsLoader.getInstance=function(){if(AssetsLoader._instance==null)AssetsLoader._instance=new AssetsLoader;return AssetsLoader._instance};AssetsLoader.prototype.onComplete=null;AssetsLoader.prototype._loadingList=null;AssetsLoader.prototype._data=null;AssetsLoader.prototype.getData=function(){return this._data};AssetsLoader.prototype.addFile=function(fileURL,fileAlias){this._data=new Object;this._loadingList.push({url:fileURL,alias:fileAlias})};
AssetsLoader.prototype.load=function(){if(this._loadingList.length==0){if(this.onComplete)this.onComplete()}else{var obj=this._loadingList.shift();var scope=this;var image=new Image;image.onload=function(){scope._onLoadComplete(image,obj.alias)};image.src=obj.url}};AssetsLoader.prototype._onLoadComplete=function(image,alias){this._data[alias]=image;this.load()};function AssetsManager(){this._images=new Object;this._atlases=new Object;this._textures=new Object}
Tomahawk.registerClass(AssetsManager,"AssetsManager");AssetsManager._instance=null;AssetsManager.getInstance=function(){if(AssetsManager._instance==null)AssetsManager._instance=new AssetsManager;return AssetsManager._instance};AssetsManager.prototype._images=null;AssetsManager.prototype._atlases=null;AssetsManager.prototype._textures=null;AssetsManager.prototype.getImages=function(){return this._images};
AssetsManager.prototype.getImageByAlias=function(alias){if(this._images[alias])return this._images[alias];return null};AssetsManager.prototype.addImage=function(image,alias){this._images[alias]=image};AssetsManager.prototype.addAtlas=function(atlas,alias){this._atlases[alias]=atlas};AssetsManager.prototype.getAtlases=function(){return this._atlases};AssetsManager.prototype.getAtlasByAlias=function(alias){if(this._atlases[alias])return this._atlases[alias];return null};
AssetsManager.prototype.addTexture=function(texture,alias){this._textures[alias]=texture};AssetsManager.prototype.getTextures=function(){return this._textures};AssetsManager.prototype.getTextureByAlias=function(alias){if(this._textures[alias])return this._textures[alias];return null};function Screen(){}Tomahawk.registerClass(Screen,"Screen");Screen.getInnerWidth=function(){return Stage.getInstance().getCanvas().parent.offsetWidth};Screen.getInnerHeight=function(){return Stage.getInstance().getCanvas().parent.offsetHeight};
Screen.getWindowWidth=function(){return window.innerWidth};function Bitmap(){}Tomahawk.registerClass(Bitmap,"Bitmap");Tomahawk.extend("Bitmap","DisplayObject");Bitmap.prototype.texture=null;Bitmap.prototype.draw=function(context){if(this.texture){var rect=this.texture.rect;var data=this.texture.data;context.drawImage(data,rect[0],rect[1],rect[2],rect[3],0,0,this.width,this.height)}};function DisplayObject(){}Tomahawk.registerClass(DisplayObject,"DisplayObject");Tomahawk.extend("DisplayObject","EventDispatcher");
DisplayObject.prototype.name=null;DisplayObject.prototype.parent=null;DisplayObject.prototype.x=0;DisplayObject.prototype.y=0;DisplayObject.prototype.pivotX=0;DisplayObject.prototype.pivotY=0;DisplayObject.prototype.skewX=0;DisplayObject.prototype.skewY=0;DisplayObject.prototype.scaleX=1;DisplayObject.prototype.scaleY=1;DisplayObject.prototype.width=0;DisplayObject.prototype.height=0;DisplayObject.prototype.rotation=0;DisplayObject.prototype.alpha=1;DisplayObject.prototype.mouseEnabled=false;
DisplayObject.prototype.visible=true;DisplayObject.prototype.handCursor=false;DisplayObject.prototype._matrix=null;DisplayObject.prototype._cache=null;DisplayObject.prototype.filters=null;DisplayObject._toRadians=Math.PI/180;
DisplayObject.prototype._applyFilters=function(){var canvas=document.createElement("canvas");var context=canvas.getContext("2d");canvas.width=this.width;canvas.height=this.height;this.draw(context);var i=0;var max=this.filters.length;var filter=null;for(;i<max;i++){filter=this.filters[i];filter.apply(canvas,context)}return canvas};
DisplayObject.prototype.render=function(context){this.update();if(this.visible==false)return;var mat=this._matrix;context.save();if(this._cache==null){context.globalAlpha=this.alpha;context.setTransform(mat.a,mat.b,mat.c,mat.d,mat.tx,mat.ty);if(this.filters!=null){var canvas=this._applyFilters();context.drawImage(canvas,0,0,canvas.width,canvas.height)}else this.draw(context)}else context.drawImage(this._cache,0,0,this._cache.width,this._cache.height);context.restore()};
DisplayObject.prototype.forceRefresh=function(){var current=this;while(current!=null){if(current._cache!=null)current.setCache(true);current=current.parent}};DisplayObject.prototype.draw=function(context){return};
DisplayObject.prototype.setCache=function(value){if(value==true){var canvas=document.createElement("canvas");var context=canvas.getContext("2d");var stageCanvas=Stage.getInstance().getCanvas();canvas.width=stageCanvas.width;canvas.height=stageCanvas.height;this.draw(context);this._cache=canvas}else this._cache=null};
DisplayObject.prototype.update=function(){var current=this;var mat=this._matrix||new Matrix2D;mat.identity();while(current!=null){mat.prependTransform(current.x,current.y,current.scaleX,current.scaleY,current.rotation,current.skewX,current.skewY,current.pivotX,current.pivotY);current=current.parent}this._matrix=mat;return this._matrix};DisplayObject.prototype.getConcatenedMatrix=function(){return this._matrix||this.update()};
DisplayObject.prototype.localToGlobal=function(x,y){var matrix=this._matrix;var pt=matrix.transformPoint(x,y);return pt};DisplayObject.prototype.globalToLocal=function(x,y){var matrix=this._matrix.clone().invert();var pt=matrix.transformPoint(x,y);return pt};DisplayObject.prototype.hitTest=function(x,y){if(this._matrix==null)this.update();var matrix=this._matrix.clone().invert();var pt1=matrix.transformPoint(x,y);if(pt1.x<0||pt1.x>this.width||pt1.y<0||pt1.y>this.height)return false;else return true};
DisplayObject.prototype.getBoundingRect=function(){var matrix=this._matrix;var pt1=matrix.transformPoint(0,0);var pt2=matrix.transformPoint(this.width,this.height);var rect=new Object;rect.left=pt1.x;rect.right=pt2.x;rect.top=pt1.y;rect.bottom=pt2.y;rect.x=pt1.x;rect.y=pt1.y;rect.width=pt2.x-pt1.x;rect.height=pt2.y-pt1.y;return rect};function DisplayObjectContainer(){this._construct()}Tomahawk.registerClass(DisplayObjectContainer,"DisplayObjectContainer");
Tomahawk.extend("DisplayObjectContainer","DisplayObject");DisplayObjectContainer.prototype.children=null;DisplayObjectContainer.prototype._construct=function(){this.children=new Array};DisplayObjectContainer.prototype.addChild=function(child){if(child.parent)child.parent.removeChild(child);child.parent=this;this.children.push(child);child.dispatchEvent(new Event(Event.ADDED,true,true))};DisplayObjectContainer.prototype.getChildAt=function(index){return this.children[index]};
DisplayObjectContainer.prototype.getChildByName=function(name){var children=this.children;var i=children.length;while(--i>-1)if(children[i].name==name)return children[i];return null};DisplayObjectContainer.prototype.hitTest=function(x,y){var children=this.children;var i=children.length;var child=null;var left=null;var top=null;var right=null;var bottom=null;var lRect=null;var rRect=null;var tRect=null;var bRect=null;while(--i>-1){child=children[i];if(child.hitTest(x,y))return true}return false};
DisplayObjectContainer.prototype.getBoundingRect=function(){var children=this.children;var i=children.length;var child=null;var rect=new Object;var childRect=null;rect.x=0;rect.y=0;rect.top=0;rect.left=0;rect.right=0;rect.bottom=0;rect.width=0;rect.height=0;i=children.length;while(--i>-1){child=children[i];rect.left=child.x<rect.left?child.x:rect.left;rect.top=child.y<rect.top?child.y:rect.top;rect.right=child.x+child.width>rect.right?child.x+child.width:rect.right;rect.bottom=child.y+child.height>
rect.bottom?child.y+child.height:rect.bottom}rect.x=rect.left;rect.y=rect.top;rect.width=rect.right-rect.left;rect.height=rect.bottom-rect.top;return rect};DisplayObjectContainer.prototype.addChildAt=function(child,index){var children=this.children;var tab1=this.children.slice(0,index);var tab2=this.children.slice(index);this.children=tab1.concat([child]).concat(tab2);child.parent=this;child.dispatchEvent(new Event(Event.ADDED,true,true))};
DisplayObjectContainer.prototype.removeChildAt=function(index){var child=this.children[index];if(child)child.parent=null;this.children.splice(index,1);child.dispatchEvent(new Event(Event.REMOVED,true,true))};DisplayObjectContainer.prototype.removeChild=function(child){var index=this.children.indexOf(child);if(index>-1)this.children.splice(index,1);child.parent=null;child.dispatchEvent(new Event(Event.REMOVED,true,true))};
DisplayObjectContainer.prototype.draw=function(context){var children=this.children;var i=0;var max=children.length;var child=null;for(;i<max;i++){child=children[i];child.render(context)}};
DisplayObjectContainer.prototype.getObjectsUnder=function(x,y,limit){var under=new Array;var children=this.children;var i=children.length;var child=null;while(--i>-1){child=children[i];if(child.getObjectsUnder)under=under.concat(child.getObjectsUnder(x,y,limit));else if(child.hitTest(x,y)==true)under.push(child);if(limit!=undefined&&under.length==limit)return under}return under};function MovieClip(){this._frames=new Array}Tomahawk.registerClass(MovieClip,"MovieClip");Tomahawk.extend("MovieClip","Bitmap");
MovieClip.prototype._frames=null;MovieClip.prototype.currentFrame=0;MovieClip.prototype._enterFrameHandler=null;MovieClip.prototype._enterFrameHandler=function(event){this.currentFrame++;if(this.currentFrame>=this._frames.length)this.currentFrame=0;if(this._frames[this.currentFrame])this.texture=this._frames[this.currentFrame]};MovieClip.prototype.setFrame=function(frameIndex,texture){this._frames[frameIndex]=texture};
MovieClip.prototype.play=function(){Stage.getInstance().addEventListener(Event.ENTER_FRAME,this,this._enterFrameHandler)};MovieClip.prototype.stop=function(){Stage.getInstance().removeEventListener(Event.ENTER_FRAME,this,this._enterFrameHandler)};function Shape(){}Tomahawk.registerClass(Shape,"Shape");Tomahawk.extend("Shape","DisplayObject");Shape.prototype._commands=null;Shape.prototype._getCommands=function(){if(this._commands==null)this._commands=new Array;return this._commands};
Shape.prototype.clear=function(){this._commands=new Array};Shape.prototype.stroke=function(){this._getCommands().push([1,"stroke",null])};Shape.prototype.fill=function(){this._getCommands().push([1,"fill",null])};Shape.prototype.beginPath=function(){this._getCommands().push([1,"beginPath",null])};Shape.prototype.closePath=function(){this._getCommands().push([1,"closePath",null])};Shape.prototype.rect=function(x,y,width,height){this._getCommands().push([1,"rect",[x,y,width,height]])};
Shape.prototype.fillRect=function(x,y,width,height){this._getCommands().push([1,"fillRect",[x,y,width,height]])};Shape.prototype.clearRect=function(x,y,width,height){this._getCommands().push([1,"clearRect",[x,y,width,height]])};Shape.prototype.strokeRect=function(x,y,width,height){this._getCommands().push([1,"strokeRect",[x,y,width,height]])};Shape.prototype.moveTo=function(x,y){this._getCommands().push([1,"moveTo",[x,y]])};
Shape.prototype.lineTo=function(x,y){this._getCommands().push([1,"lineTo",[x,y]])};Shape.prototype.arc=function(x,y,radius,startAngle,endAngle,antiClockwise){this._getCommands().push([1,"arc",[x,y,radius,startAngle,endAngle,antiClockwise]])};Shape.prototype.arcTo=function(controlX,controlY,endX,endY,radius){this._getCommands().push([1,"arcTo",[controlX,controlY,endX,endY,radius]])};
Shape.prototype.quadraticCurveTo=function(controlX,controlY,endX,endY){this._getCommands().push([1,"quadraticCurveTo",[controlX,controlY,endX,endY]])};Shape.prototype.bezierCurveTo=function(controlX1,controlY1,controlX2,controlY2,endX,endY){this._getCommands().push([1,"bezierCurveTo",[controlX1,controlY1,controlX2,controlY2,endX,endY]])};Shape.prototype.addColorStop=function(offset,color){this._getCommands().push([1,"addColorStop",[offset,color]])};
Shape.prototype.createLinearGradient=function(startX,startY,endX,endY){this._getCommands().push([1,"createLinearGradient",[startX,startY,endX,endY]])};Shape.prototype.createRadialGradient=function(startX,startY,startRadius,endX,endY,endRadius){this._getCommands().push([1,"createRadialGradient",[startX,startY,startRadius,endX,endY,endRadius]])};Shape.prototype.lineWidth=function(value){this._getCommands().push([0,"lineWidth",value])};
Shape.prototype.lineColor=function(value){this._getCommands().push([0,"lineColor",value])};Shape.prototype.lineCap=function(value){this._getCommands().push([0,"lineCap",value])};Shape.prototype.lineJoin=function(value){this._getCommands().push([0,"lineJoin",value])};Shape.prototype.strokeStyle=function(value){this._getCommands().push([0,"strokeStyle",value])};Shape.prototype.fillStyle=function(value){this._getCommands().push([0,"fillStyle",value])};
Shape.prototype.draw=function(context){var commands=this._getCommands();var command=null;var i=0;var max=commands.length;var type=null;var prop=null;var args=null;for(i=0;i<max;i++){command=commands[i];type=command[0];prop=command[1];args=command[2];if(type==0)context[prop]=args;else context[prop].apply(context,args)}};
function Stage(){window.requestAnimationFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback,element){window.setTimeout(callback,10)}}();this._construct()}Tomahawk.registerClass(Stage,"Stage");Tomahawk.extend("Stage","DisplayObjectContainer");Stage._instance=null;Stage.getInstance=function(){if(Stage._instance==null)Stage._instance=new Stage;return Stage._instance};
Stage.prototype._lastTime=0;Stage.prototype._frameCount=0;Stage.prototype._fps=0;Stage.prototype._canvas=null;Stage.prototype._context=null;Stage.prototype._debug=false;Stage.prototype._lastActiveChild=null;Stage.prototype.displayMouseCoordinates=false;Stage.prototype.mouseX=0;Stage.prototype.mouseY=0;Stage.prototype._input=null;
Stage.prototype.init=function(canvas){var scope=this;var callback=function(event){scope._mouseHandler(event)};var callbackKey=function(event){scope._keyboardHandler(event)};this._input=document.createElement("input");this._input.type="text";this._canvas=canvas;this._context=canvas.getContext("2d");this.addEventListener(Event.ADDED,this,this._eventHandler,true);this._canvas.addEventListener("click",callback);this._canvas.addEventListener("mousemove",callback);this._canvas.addEventListener("mousedown",
callback);this._canvas.addEventListener("mouseup",callback);this._canvas.addEventListener("dblclick",callback);window.addEventListener("keyup",callbackKey);window.addEventListener("keydown",callbackKey);window.addEventListener("keypress",callbackKey);this._enterFrame()};
Stage.prototype._keyboardHandler=function(event){event.preventDefault();event.stopImmediatePropagation();event.stopPropagation();if(event.type=="keyup")Keyboard.toggleShift(event.keyCode);var keyboardEvent=KeyEvent.fromNativeMouseEvent(event,true,true);keyboardEvent.value=Keyboard.keyCodeToChar(event.keyCode,event.shiftKey,event.ctrlKey,event.altKey);this.dispatchEvent(keyboardEvent)};
Stage.prototype._mouseHandler=function(event){event.preventDefault();event.stopImmediatePropagation();event.stopPropagation();var bounds=this._canvas.getBoundingClientRect();var x=event.clientX-bounds.left;var y=event.clientY-bounds.top;var activeChild=this._getMouseObjectUnder(x,y,this);var mouseEvent=null;var i=0;this._lastMouseX=this.mouseX>>0;this._lastMouseY=this.mouseY>>0;this.mouseX=x>>0;this.mouseY=y>>0;if(event.type=="mousemove"&&this._lastActiveChild!=activeChild){if(activeChild!=null){mouseEvent=
MouseEvent.fromNativeMouseEvent(event,true,true,x,y);mouseEvent.type=MouseEvent.ROLL_OVER;activeChild.dispatchEvent(mouseEvent)}if(this._lastActiveChild!=null){mouseEvent=MouseEvent.fromNativeMouseEvent(event,true,true,x,y);mouseEvent.type=MouseEvent.ROLL_OUT;this._lastActiveChild.dispatchEvent(mouseEvent)}}else if(activeChild!=null){mouseEvent=MouseEvent.fromNativeMouseEvent(event,true,true,x,y);activeChild.dispatchEvent(mouseEvent)}if(event.type=="mousedown")this._lastMouseDownChild=activeChild;
if(event.type=="mouseup"&&activeChild!=this._lastMouseDownChild&&this._lastMouseDownChild!=null){mouseEvent=MouseEvent.fromNativeMouseEvent(event,true,true,x,y);mouseEvent.type==MouseEvent.RELEASE_OUTSIDE;this._lastMouseDownChild.dispatchEvent(mouseEvent);this._lastMouseDownChild=null}this._lastActiveChild=activeChild};Stage.prototype.getMovement=function(){var pt=new Object;pt.x=this.mouseX-this._lastMouseX;pt.y=this.mouseY-this._lastMouseY;return pt};
Stage.prototype._getMouseObjectUnder=function(x,y,container){var under=null;var children=container.children;var i=children.length;var child=null;while(--i>-1){child=children[i];if(child.children){under=this._getMouseObjectUnder(x,y,child);if(under!=null)return under}else if(child.mouseEnabled==true&&child.hitTest(x,y)==true)return child}return null};
Stage.prototype._eventHandler=function(event){switch(event.type){case Event.ADDED:event.target.dispatchEvent(new Event(Event.ADDED_TO_STAGE,true,true));break;case Event.REMOVED:event.target.dispatchEvent(new Event(Event.REMOVED_FROM_STAGE,true,true));break}};
Stage.prototype._enterFrame=function(){this.dispatchEvent(new Event(Event.ENTER_FRAME,true,true));var curTime=(new Date).getTime();var scope=this;this._frameCount++;if(curTime-this._lastTime>=1E3){this._fps=this._frameCount;this._frameCount=0;this._lastTime=curTime}this._context.clearRect(0,0,this._canvas.width,this._canvas.height);this._context.save();this.render(this._context);this._context.restore();if(this._debug==true){this._context.save();this._context.beginPath();this._context.fillStyle="black";
this._context.fillRect(0,0,100,30);this._context.fill();this._context.fillStyle="red";this._context.font="italic 20pt Calibri";this._context.fillText("fps: "+this._fps,0,30);this._context.restore()}if(this.displayMouseCoordinates==true){this._context.save();this._context.beginPath();this._context.fillStyle="green";this._context.fillRect(this.mouseX-2,this.mouseY-2,4,4);this._context.fill();this._context.restore()}window.requestAnimationFrame(function(){scope._enterFrame()})};
Stage.prototype.getCanvas=function(){return this._canvas};Stage.prototype.getContext=function(){return this._context};Stage.prototype.getFPS=function(){return this._fps};Stage.prototype.setDebug=function(debug){this._debug=debug};function Event(type,bubbles,cancelable){this.type=type;this.cancelable=cancelable;this.bubbles=bubbles}Tomahawk.registerClass(Event,"Event");Event.prototype.type=null;Event.prototype.bubbles=false;Event.prototype.cancelable=true;Event.prototype.data=null;
Event.prototype.target=null;Event.prototype.currentTarget=null;Event.prototype.stopPropagation=function(){if(this.cancelable==true)this.bubbles=false};Event.FOCUSED="focused";Event.UNFOCUSED="unfocused";Event.ADDED="added";Event.ADDED_TO_STAGE="addedToStage";Event.ENTER_FRAME="enterFrame";Event.REMOVED="removed";Event.REMOVED_FROM_STAGE="removedFromStage";function EventDispatcher(){}Tomahawk.registerClass(EventDispatcher,"EventDispatcher");EventDispatcher.prototype.parent=null;
EventDispatcher.prototype._listeners=null;EventDispatcher.prototype.addEventListener=function(type,scope,callback,useCapture){this._listeners=this._listeners||new Array;var obj=new Object;obj.type=type;obj.scope=scope;obj.callback=callback;obj.useCapture=useCapture;this._listeners.push(obj)};EventDispatcher.prototype.hasEventListener=function(type){if(this._listeners==null)return false;var obj=new Object;var i=this._listeners.length;while(--i>-1){obj=this._listeners[i];if(obj.type==type)return true}};
EventDispatcher.prototype.dispatchEvent=function(event){this._listeners=this._listeners||new Array;var obj=new Object;var i=this._listeners.length;var toDispatch=new Array;if(event.target==null)event.target=this;event.currentTarget=this;while(--i>-1){obj=this._listeners[i];if(obj.type==event.type){if(event.target!=this&&obj.useCapture==false)continue;toDispatch.push(obj)}}i=toDispatch.length;while(--i>-1){obj=toDispatch[i];obj.callback.apply(obj.scope,[event])}if(event.bubbles==true&&this.parent!=
null&&this.parent.dispatchEvent)this.parent.dispatchEvent(event)};EventDispatcher.prototype.removeEventListener=function(type,scope,callback,useCapture){var obj=new Object;var i=this._listeners.length;var arr=new Array;while(--i>-1){obj=this._listeners[i];if(obj.type!=type||obj.scope!=scope||obj.callback!=callback||obj.useCapture!=useCapture)arr.push(obj)}this._listeners=arr};function KeyEvent(type,bubbles,cancelable){this.type=type;this.cancelable=cancelable;this.bubbles=bubbles}
Tomahawk.registerClass(KeyEvent,"KeyEvent");Tomahawk.extend("Keyboard","Event");KeyEvent.prototype.value="";KeyEvent.prototype.keyCode=0;KeyEvent.prototype.charCode=0;KeyEvent.prototype.crtlKey=false;KeyEvent.prototype.shiftKey=false;
KeyEvent.fromNativeMouseEvent=function(event,bubbles,cancelable){var type="";var newEvent=null;switch(event.type){case "keyup":type=KeyEvent.KEY_UP;break;case "keypress":type=KeyEvent.KEY_PRESS;break;case "keydown":type=KeyEvent.KEY_DOWN;break}newEvent=new KeyEvent(type,bubbles,cancelable);newEvent.keyCode=event.keyCode;newEvent.charCode=event.charCode;newEvent.ctrlKey=event.ctrlKey;newEvent.shiftKey=event.shiftKey;newEvent.which=event.which;return newEvent};KeyEvent.KEY_UP="keyup";
KeyEvent.KEY_DOWN="keydown";KeyEvent.KEY_PRESS="keypress";function Keyboard(){}Keyboard.keyCodeToChar=function(keyCode,shiftKey,ctrlKey,altKey){var obj=Keyboard.MAP[keyCode];var altgr=ctrlKey&&altKey;if(obj==undefined)return"";if(altgr)return obj.altgr;if(shiftKey||Keyboard._majActive)return obj.shift;return obj.normal};Keyboard.isChar=function(keyCode){if(Keyboard.MAP[keyCode])return true;return false};Keyboard.toggleShift=function(keyCode){if(keyCode==Keyboard.CAPSLOCK)Keyboard._majActive=!Keyboard._majActive};
Keyboard._majActive=false;Keyboard.BACKSPACE=8;Keyboard.TAB=9;Keyboard.ENTER=13;Keyboard.SHIFT=16;Keyboard.CTRL=17;Keyboard.ALT=18;Keyboard.CAPSLOCK=20;Keyboard.SPACE=32;Keyboard.END=35;Keyboard.START=36;Keyboard.LEFT=37;Keyboard.UP=38;Keyboard.RIGHT=39;Keyboard.DOWN=40;Keyboard.SUPPR=46;Keyboard.TOUCH_0=48;Keyboard.TOUCH_1=49;Keyboard.TOUCH_2=50;Keyboard.TOUCH_3=51;Keyboard.TOUCH_4=52;Keyboard.TOUCH_5=53;Keyboard.TOUCH_6=54;Keyboard.TOUCH_7=55;Keyboard.TOUCH_8=56;Keyboard.TOUCH_9=57;Keyboard.A=65;
Keyboard.B=66;Keyboard.C=67;Keyboard.D=68;Keyboard.E=69;Keyboard.F=70;Keyboard.G=71;Keyboard.H=72;Keyboard.I=73;Keyboard.J=74;Keyboard.K=75;Keyboard.L=76;Keyboard.M=77;Keyboard.N=78;Keyboard.O=79;Keyboard.P=80;Keyboard.Q=81;Keyboard.R=82;Keyboard.S=83;Keyboard.T=84;Keyboard.U=85;Keyboard.V=86;Keyboard.W=87;Keyboard.X=88;Keyboard.Y=89;Keyboard.Z=90;Keyboard.WINDOWS=91;Keyboard.SELECT=93;Keyboard.NUMPAD_0=96;Keyboard.NUMPAD_1=97;Keyboard.NUMPAD_2=98;Keyboard.NUMPAD_3=99;Keyboard.NUMPAD_4=100;
Keyboard.NUMPAD_5=101;Keyboard.NUMPAD_6=102;Keyboard.NUMPAD_7=103;Keyboard.NUMPAD_8=104;Keyboard.NUMPAD_9=105;Keyboard.NUMPAD_MULTIPLY=106;Keyboard.NUMPAD_PLUS=107;Keyboard.NUMPAD_MINUS=109;Keyboard.NUMPAD_DOT=110;Keyboard.NUMPAD_SLASH=111;Keyboard.F1=112;Keyboard.F2=113;Keyboard.F3=114;Keyboard.F4=115;Keyboard.F5=116;Keyboard.F6=117;Keyboard.F7=118;Keyboard.F8=119;Keyboard.F9=120;Keyboard.F10=121;Keyboard.F11=122;Keyboard.F12=123;Keyboard.VERR_NUM=144;Keyboard.DOLLAR=186;Keyboard.EQUAL=187;
Keyboard.QUESTION=188;Keyboard.DOT=190;Keyboard.SLASH=191;Keyboard.PERCENT=192;Keyboard.RIGHT_PARENT=219;Keyboard.MICRO=220;Keyboard.TREMA=221;Keyboard.POWER_TWO=222;Keyboard.EXCLAMATION=223;Keyboard.MAP=new Array;Keyboard.MAP[Keyboard.TOUCH_0]={normal:"\u00e0",shift:"0",altgr:"@"};Keyboard.MAP[Keyboard.TOUCH_1]={normal:"&",shift:"1",altgr:""};Keyboard.MAP[Keyboard.TOUCH_2]={normal:"\u00e9",shift:"2",altgr:"~"};Keyboard.MAP[Keyboard.TOUCH_3]={normal:'"',shift:"3",altgr:"#"};
Keyboard.MAP[Keyboard.TOUCH_4]={normal:"'",shift:"4",altgr:"{"};Keyboard.MAP[Keyboard.TOUCH_5]={normal:"(",shift:"5",altgr:"["};Keyboard.MAP[Keyboard.TOUCH_6]={normal:"-",shift:"6",altgr:"|"};Keyboard.MAP[Keyboard.TOUCH_7]={normal:"\u00e8",shift:"7",altgr:"`"};Keyboard.MAP[Keyboard.TOUCH_8]={normal:"_",shift:"8",altgr:"\\"};Keyboard.MAP[Keyboard.TOUCH_9]={normal:"\u00e7",shift:"9",altgr:"^"};Keyboard.MAP[Keyboard.A]={normal:"a",shift:"A",altgr:""};Keyboard.MAP[Keyboard.B]={normal:"b",shift:"B",altgr:""};
Keyboard.MAP[Keyboard.C]={normal:"c",shift:"C",altgr:""};Keyboard.MAP[Keyboard.D]={normal:"d",shift:"D",altgr:""};Keyboard.MAP[Keyboard.E]={normal:"e",shift:"E",altgr:""};Keyboard.MAP[Keyboard.F]={normal:"f",shift:"F",altgr:""};Keyboard.MAP[Keyboard.G]={normal:"g",shift:"G",altgr:""};Keyboard.MAP[Keyboard.H]={normal:"h",shift:"H",altgr:""};Keyboard.MAP[Keyboard.I]={normal:"i",shift:"I",altgr:""};Keyboard.MAP[Keyboard.J]={normal:"j",shift:"J",altgr:""};
Keyboard.MAP[Keyboard.K]={normal:"k",shift:"K",altgr:""};Keyboard.MAP[Keyboard.L]={normal:"l",shift:"L",altgr:""};Keyboard.MAP[Keyboard.M]={normal:"m",shift:"M",altgr:""};Keyboard.MAP[Keyboard.N]={normal:"n",shift:"N",altgr:""};Keyboard.MAP[Keyboard.O]={normal:"o",shift:"O",altgr:""};Keyboard.MAP[Keyboard.P]={normal:"p",shift:"P",altgr:""};Keyboard.MAP[Keyboard.Q]={normal:"q",shift:"Q",altgr:""};Keyboard.MAP[Keyboard.R]={normal:"r",shift:"R",altgr:""};
Keyboard.MAP[Keyboard.S]={normal:"s",shift:"S",altgr:""};Keyboard.MAP[Keyboard.T]={normal:"t",shift:"T",altgr:""};Keyboard.MAP[Keyboard.U]={normal:"u",shift:"U",altgr:""};Keyboard.MAP[Keyboard.V]={normal:"v",shift:"V",altgr:""};Keyboard.MAP[Keyboard.W]={normal:"w",shift:"W",altgr:""};Keyboard.MAP[Keyboard.X]={normal:"x",shift:"X",altgr:""};Keyboard.MAP[Keyboard.Y]={normal:"y",shift:"Y",altgr:""};Keyboard.MAP[Keyboard.Z]={normal:"z",shift:"Z",altgr:""};
Keyboard.MAP[Keyboard.DOLLAR]={normal:"$",shift:"\u00a3",altgr:"\u00a4"};Keyboard.MAP[Keyboard.EQUAL]={normal:"=",shift:"+",altgr:"}"};Keyboard.MAP[Keyboard.QUESTION]={normal:",",shift:"?",altgr:""};Keyboard.MAP[Keyboard.DOT]={normal:";",shift:".",altgr:""};Keyboard.MAP[Keyboard.SLASH]={normal:":",shift:"/",altgr:""};Keyboard.MAP[Keyboard.EXCLAMATION]={normal:"!",shift:"\u00a7",altgr:""};Keyboard.MAP[Keyboard.POWER_TWO]={normal:"!",shift:"\u00a7",altgr:""};
Keyboard.MAP[Keyboard.PERCENT]={normal:"\u00f9",shift:"%",altgr:""};Keyboard.MAP[Keyboard.RIGHT_PARENT]={normal:")",shift:"\u00b0",altgr:"]"};Keyboard.MAP[Keyboard.MICRO]={normal:"*",shift:"\u00b5",altgr:""};Keyboard.MAP[Keyboard.TREMA]={normal:"^",shift:"\u00a8",altgr:""};Keyboard.MAP[Keyboard.NUMPAD_0]={normal:"0",shift:"0",altgr:"0"};Keyboard.MAP[Keyboard.NUMPAD_1]={normal:"1",shift:"1",altgr:"1"};Keyboard.MAP[Keyboard.NUMPAD_2]={normal:"2",shift:"2",altgr:"2"};
Keyboard.MAP[Keyboard.NUMPAD_3]={normal:"3",shift:"3",altgr:"3"};Keyboard.MAP[Keyboard.NUMPAD_4]={normal:"4",shift:"4",altgr:"4"};Keyboard.MAP[Keyboard.NUMPAD_5]={normal:"5",shift:"5",altgr:"5"};Keyboard.MAP[Keyboard.NUMPAD_6]={normal:"6",shift:"6",altgr:"6"};Keyboard.MAP[Keyboard.NUMPAD_7]={normal:"7",shift:"7",altgr:"7"};Keyboard.MAP[Keyboard.NUMPAD_8]={normal:"8",shift:"8",altgr:"8"};Keyboard.MAP[Keyboard.NUMPAD_9]={normal:"9",shift:"9",altgr:"9"};
Keyboard.MAP[Keyboard.NUMPAD_MULTIPLY]={normal:"*",shift:"*",altgr:"*"};Keyboard.MAP[Keyboard.NUMPAD_SLASH]={normal:"/",shift:"/",altgr:"/"};Keyboard.MAP[Keyboard.NUMPAD_PLUS]={normal:"+",shift:"+",altgr:"+"};Keyboard.MAP[Keyboard.NUMPAD_MINUS]={normal:"-",shift:"-",altgr:"-"};Keyboard.MAP[Keyboard.NUMPAD_DOT]={normal:".",shift:".",altgr:"."};Keyboard.MAP[Keyboard.SPACE]={normal:" ",shift:" ",altgr:" "};Keyboard.MAP[Keyboard.ENTER]={normal:"\u00a4",shift:"\u00a4",altgr:"\u00a4"};
function MouseEvent(){}Tomahawk.registerClass(MouseEvent,"MouseEvent");Tomahawk.extend("MouseEvent","Event");function MouseEvent(type,bubbles,cancelable){this.type=type;this.cancelable=cancelable;this.bubbles=bubbles}
MouseEvent.fromNativeMouseEvent=function(event,bubbles,cancelable,x,y){var type="";var msevent=null;switch(event.type){case "click":type=MouseEvent.CLICK;break;case "dblclick":type=MouseEvent.DOUBLE_CLICK;break;case "mousemove":type=MouseEvent.MOUSE_MOVE;break;case "mouseup":type=MouseEvent.MOUSE_UP;break;case "mousedown":type=MouseEvent.MOUSE_DOWN;break}msevent=new MouseEvent(type,bubbles,cancelable);msevent.stageX=x;msevent.stageY=y;return msevent};MouseEvent.CLICK="click";
MouseEvent.DOUBLE_CLICK="doubleClick";MouseEvent.ROLL_OVER="rollOver";MouseEvent.ROLL_OUT="rollOut";MouseEvent.MOUSE_MOVE="mouseMove";MouseEvent.MOUSE_UP="mouseUp";MouseEvent.MOUSE_DOWN="mouseDown";function GrayScaleFilter(){}Tomahawk.registerClass(GrayScaleFilter,"GrayScaleFilter");Tomahawk.extend(GrayScaleFilter,"PixelFilter");
GrayScaleFilter.prototype.process=function(){var pixels=this.getPixels();var data=pixels.data;for(var i=0;i<data.length;i+=4){var r=data[i];var g=data[i+1];var b=data[i+2];var v=0.2126*r+0.7152*g+0.0722*b;data[i]=data[i+1]=data[i+2]=v}this.setPixels(pixels)};function PixelFilter(){}Tomahawk.registerClass(PixelFilter,"PixelFilter");PixelFilter.prototype._canvas=null;PixelFilter.prototype._context=null;
PixelFilter.prototype.getPixels=function(){return this._context.getImageData(0,0,this._canvas.width,this._canvas.height)};PixelFilter.prototype.setPixels=function(pixels){context.putImageData(pixels,0,0)};PixelFilter.prototype.process=function(){};PixelFilter.prototype.apply=function(canvas,context){this._canvas=canvas;this._context=context;this.process()};function Matrix2D(a,b,c,d,tx,ty){this.initialize(a,b,c,d,tx,ty)}Matrix2D.prototype.identity=null;Matrix2D.DEG_TO_RAD=Math.PI/180;
Matrix2D.prototype.a=1;Matrix2D.prototype.b=0;Matrix2D.prototype.c=0;Matrix2D.prototype.d=1;Matrix2D.prototype.tx=0;Matrix2D.prototype.ty=0;Matrix2D.prototype.initialize=function(a,b,c,d,tx,ty){this.a=a==null?1:a;this.b=b||0;this.c=c||0;this.d=d==null?1:d;this.tx=tx||0;this.ty=ty||0;return this};
Matrix2D.prototype.prepend=function(a,b,c,d,tx,ty){var tx1=this.tx;if(a!=1||b!=0||c!=0||d!=1){var a1=this.a;var c1=this.c;this.a=a1*a+this.b*c;this.b=a1*b+this.b*d;this.c=c1*a+this.d*c;this.d=c1*b+this.d*d}this.tx=tx1*a+this.ty*c+tx;this.ty=tx1*b+this.ty*d+ty;return this};
Matrix2D.prototype.append=function(a,b,c,d,tx,ty){var a1=this.a;var b1=this.b;var c1=this.c;var d1=this.d;this.a=a*a1+b*c1;this.b=a*b1+b*d1;this.c=c*a1+d*c1;this.d=c*b1+d*d1;this.tx=tx*a1+ty*c1+this.tx;this.ty=tx*b1+ty*d1+this.ty;return this};Matrix2D.prototype.prependMatrix=function(matrix){this.prepend(matrix.a,matrix.b,matrix.c,matrix.d,matrix.tx,matrix.ty);return this};Matrix2D.prototype.appendMatrix=function(matrix){this.append(matrix.a,matrix.b,matrix.c,matrix.d,matrix.tx,matrix.ty);return this};
Matrix2D.prototype.prependTransform=function(x,y,scaleX,scaleY,rotation,skewX,skewY,regX,regY){if(rotation%360){var r=rotation*Matrix2D.DEG_TO_RAD;var cos=Math.cos(r);var sin=Math.sin(r)}else{cos=1;sin=0}if(regX||regY){this.tx-=regX;this.ty-=regY}if(skewX||skewY){skewX*=Matrix2D.DEG_TO_RAD;skewY*=Matrix2D.DEG_TO_RAD;this.prepend(cos*scaleX,sin*scaleX,-sin*scaleY,cos*scaleY,0,0);this.prepend(Math.cos(skewY),Math.sin(skewY),-Math.sin(skewX),Math.cos(skewX),x,y)}else this.prepend(cos*scaleX,sin*scaleX,
-sin*scaleY,cos*scaleY,x,y);return this};
Matrix2D.prototype.appendTransform=function(x,y,scaleX,scaleY,rotation,skewX,skewY,regX,regY){if(rotation%360){var r=rotation*Matrix2D.DEG_TO_RAD;var cos=Math.cos(r);var sin=Math.sin(r)}else{cos=1;sin=0}if(skewX||skewY){skewX*=Matrix2D.DEG_TO_RAD;skewY*=Matrix2D.DEG_TO_RAD;this.append(Math.cos(skewY),Math.sin(skewY),-Math.sin(skewX),Math.cos(skewX),x,y);this.append(cos*scaleX,sin*scaleX,-sin*scaleY,cos*scaleY,0,0)}else this.append(cos*scaleX,sin*scaleX,-sin*scaleY,cos*scaleY,x,y);if(regX||regY){this.tx-=
regX*this.a+regY*this.c;this.ty-=regX*this.b+regY*this.d}return this};Matrix2D.prototype.rotate=function(angle){var cos=Math.cos(angle);var sin=Math.sin(angle);var a1=this.a;var c1=this.c;var tx1=this.tx;this.a=a1*cos-this.b*sin;this.b=a1*sin+this.b*cos;this.c=c1*cos-this.d*sin;this.d=c1*sin+this.d*cos;this.tx=tx1*cos-this.ty*sin;this.ty=tx1*sin+this.ty*cos;return this};
Matrix2D.prototype.skew=function(skewX,skewY){skewX=skewX*Matrix2D.DEG_TO_RAD;skewY=skewY*Matrix2D.DEG_TO_RAD;this.append(Math.cos(skewY),Math.sin(skewY),-Math.sin(skewX),Math.cos(skewX),0,0);return this};Matrix2D.prototype.scale=function(x,y){this.a*=x;this.d*=y;this.c*=x;this.b*=y;this.tx*=x;this.ty*=y;return this};Matrix2D.prototype.translate=function(x,y){this.tx+=x;this.ty+=y;return this};Matrix2D.prototype.identity=function(){this.a=this.d=1;this.b=this.c=this.tx=this.ty=0;return this};
Matrix2D.prototype.invert=function(){var a1=this.a;var b1=this.b;var c1=this.c;var d1=this.d;var tx1=this.tx;var n=a1*d1-b1*c1;this.a=d1/n;this.b=-b1/n;this.c=-c1/n;this.d=a1/n;this.tx=(c1*this.ty-d1*tx1)/n;this.ty=-(a1*this.ty-b1*tx1)/n;return this};Matrix2D.prototype.isIdentity=function(){return this.tx==0&&this.ty==0&&this.a==1&&this.b==0&&this.c==0&&this.d==1};Matrix2D.prototype.transformPoint=function(x,y,pt){pt=pt||{};pt.x=x*this.a+y*this.c+this.tx;pt.y=x*this.b+y*this.d+this.ty;return pt};
Matrix2D.prototype.decompose=function(target){if(target==null)target={};target.x=this.tx;target.y=this.ty;target.scaleX=Math.sqrt(this.a*this.a+this.b*this.b);target.scaleY=Math.sqrt(this.c*this.c+this.d*this.d);var skewX=Math.atan2(-this.c,this.d);var skewY=Math.atan2(this.b,this.a);if(skewX==skewY){target.rotation=skewY/Matrix2D.DEG_TO_RAD;if(this.a<0&&this.d>=0)target.rotation+=target.rotation<=0?180:-180;target.skewX=target.skewY=0}else{target.skewX=skewX/Matrix2D.DEG_TO_RAD;target.skewY=skewY/
Matrix2D.DEG_TO_RAD}return target};Matrix2D.prototype.reinitialize=function(a,b,c,d,tx,ty){this.initialize(a,b,c,d,tx,ty);return this};Matrix2D.prototype.copy=function(matrix){return this.reinitialize(matrix.a,matrix.b,matrix.c,matrix.d,matrix.tx,matrix.ty)};Matrix2D.prototype.clone=function(){return(new Matrix2D).copy(this)};Matrix2D.prototype.toString=function(){return"[Matrix2D (a="+this.a+" b="+this.b+" c="+this.c+" d="+this.d+" tx="+this.tx+" ty="+this.ty+")]"};Matrix2D.identity=new Matrix2D;
function InputText(){TextField.apply(this);this._initListeners()}Tomahawk.registerClass(InputText,"InputText");Tomahawk.extend("InputText","TextField");InputText.prototype.currentIndex=0;InputText.prototype._cursorVisible=false;InputText.prototype._lastTime=0;InputText.prototype._down=false;InputText.prototype._ignoreNextClick=false;InputText.prototype._startPoint=null;InputText.prototype.focused=false;
InputText.prototype._initListeners=function(){Stage.getInstance().addEventListener(MouseEvent.DOUBLE_CLICK,this,this._mouseEventHandler,true);this.addEventListener(MouseEvent.CLICK,this,this._mouseEventHandler,true);this.addEventListener(MouseEvent.MOUSE_DOWN,this,this._mouseEventHandler,true);Stage.getInstance().addEventListener(MouseEvent.MOUSE_UP,this,this._mouseEventHandler,true);Stage.getInstance().addEventListener(MouseEvent.MOUSE_MOVE,this,this._mouseEventHandler,true);Stage.getInstance().addEventListener(KeyEvent.KEY_DOWN,
this,this._keyHandler)};InputText.prototype.getLettersIn=function(x,y,width,height){var i=0;var letters=new Array;var max=this._letters.length;var letterObj=null;for(i=0;i<max;i++){letterObj=this._letters[i];if(letterObj.x>x+width||letterObj.x+letterObj.width<x||letterObj.y<y||letterObj.y-letterObj.height>y+height)continue;letters.push(letterObj)}return letters};
InputText.prototype._drawText=function(context){TextField.prototype._drawText.apply(this,[context]);this.currentIndex=this.currentIndex>this._letters.length-1?this._letters.length-1:this.currentIndex;var letterObj=this._letters[this.currentIndex];var time=(new Date).getTime();if(time-this._lastTime>500){this._lastTime=time;this._cursorVisible=!this._cursorVisible}if(this._cursorVisible==true&&letterObj&&this.focused){var selected=this.currentIndex>=this._selectStart&&this.currentIndex<=this._selectEnd?
true:false;context.save();context.strokeStyle=selected?"white":"black";context.moveTo(letterObj.x+letterObj.width,letterObj.y);context.lineTo(letterObj.x+letterObj.width,letterObj.y-letterObj.height);context.stroke();context.restore()}};
InputText.prototype._keyHandler=function(event){if(this.focused==false)return;if(event.keyCode==Keyboard.BACKSPACE){var start=this.currentIndex;var end=this.currentIndex+1;var sub1=null;var sub2=null;this.currentIndex--;if(this._selectStart!=-1){start=this._selectStart;end=this._selectEnd+1;this._selectStart=this._selectEnd=-1}sub1=this.text.substr(0,start);sub2=this.text.substr(end);this._formats.splice(start,end-start);this.currentIndex=start-1;this.text=sub1+sub2}else if(event.keyCode==Keyboard.LEFT)this.currentIndex--;
else if(event.keyCode==Keyboard.RIGHT)this.currentIndex++;else{var sub1=this.text.substr(0,this.currentIndex+1);var sub2=this.text.substr(this.currentIndex+1);var format=this.getTextFormat(this.currentIndex);this.text=sub1+event.value+sub2;this.setTextFormat(format,this.currentIndex,this.currentIndex+1);this.currentIndex+=event.value.length}};
InputText.prototype._mouseEventHandler=function(event){if(event.type==MouseEvent.DOUBLE_CLICK)this.focused=event.target==this;if(this.focused==false)return;if(event.type==MouseEvent.MOUSE_UP)this._down=false;if(event.type==MouseEvent.CLICK){this._down=false;if(this._ignoreNextClick==true)this._ignoreNextClick=false;else{var pt=this.globalToLocal(event.stageX,event.stageY);var letters=this.getLettersIn(pt.x,pt.y,1,1);this._selectStart=this._selectEnd=-1;if(letters.length>0)this.currentIndex=letters[0].index}}if(event.type==
MouseEvent.MOUSE_DOWN){this._down=true;this._startPoint=this.globalToLocal(event.stageX,event.stageY);return}if(event.type==MouseEvent.MOUSE_MOVE&&this._down==true&&this._startPoint!=null){var endPoint=this.globalToLocal(event.stageX,event.stageY);var x=endPoint.x<this._startPoint.x?endPoint.x:this._startPoint.x;var x2=endPoint.x<this._startPoint.x?this._startPoint.x:endPoint.x;var y=endPoint.y<this._startPoint.y?endPoint.y:this._startPoint.y;var y2=endPoint.y<this._startPoint.y?this._startPoint.y:
endPoint.y;var width=x2-x;var height=y2-y;var letters=this.getLettersIn(x,y,width,height);var start=-1;var end=-1;var i=letters.length;var letterObj=null;while(--i>-1){letterObj=letters[i];start=letterObj.index<start||start==-1?letterObj.index:start;end=letterObj.index>end||end==-1?letterObj.index:end}this._selectStart=start;this._selectEnd=end;this._ignoreNextClick=true}};function Letter(){}Tomahawk.registerClass(Letter,"Letter");Letter.prototype.newline=false;Letter.prototype.index=0;
Letter.prototype.x=0;Letter.prototype.y=0;Letter.prototype.value="";Letter.prototype.row=0;Letter.prototype.width=0;Letter.prototype.height=0;function TextField(){this.defaultTextFormat=new TextFormat;this._formats=new Array}Tomahawk.registerClass(TextField,"TextField");Tomahawk.extend("TextField","DisplayObject");TextField.NEW_LINE_CHARACTER="\u00a4";TextField.prototype._lineMetrics=null;TextField.prototype._letters=null;TextField.prototype._formats=null;TextField.prototype._textHeight=0;
TextField.prototype._selectStart=-1;TextField.prototype._selectEnd=-1;TextField.prototype.text="";TextField.prototype.padding=5;TextField.prototype.background=true;TextField.prototype.backgroundColor="#ffffff";TextField.prototype.border=true;TextField.prototype.borderColor="#000000";TextField.prototype.defaultTextFormat=null;
TextField.prototype.draw=function(context){context.save();if(this.background==true){context.save();context.beginPath();context.fillStyle=this.backgroundColor;context.fillRect(0,0,this.width,this.height);context.fill();context.restore()}if(this.border==true){context.save();context.beginPath();context.strokeStyle=this.borderColor;context.moveTo(0,0);context.lineTo(this.width,0);context.lineTo(this.width,this.height);context.lineTo(0,this.height);context.lineTo(0,0);context.stroke();context.restore()}this._drawText(context);
context.restore()};TextField.prototype.setTextFormat=function(format,startIndex,endIndex){startIndex=startIndex||0;endIndex=endIndex||this.text.length;var i=startIndex;var max=endIndex+1;for(;i<max;i++)this._formats[i]=format};TextField.prototype.getTextFormat=function(index){return this._formats[index]||this.defaultTextFormat};
TextField.prototype.getMaxLineHeight=function(context){context.save();this.defaultTextFormat.updateContext(context);var i=this._formats.length;var currentFormat=null;var height=context.measureText("M").width;var curHeight=-1;while(--i>-1){currentFormat=this._formats[i]||this.defaultTextFormat;currentFormat.updateContext(context);curHeight=context.measureText("M").width;height=height<curHeight?curHeight:height}context.restore();return height};TextField.prototype.getTextHeight=function(){return this._textHeight};
TextField.prototype._updateMetrics=function(context){var x=this.padding;var y=0;var textWidth=0;var lineHeight=0;var curLineHeight=0;var lines=new Array;var letters=new Array;var letterObj=null;var currentFormat=null;var i=0;var max=this.text.length;var currentRow=0;var currentChar="";for(i=0;i<max;i++){context.save();currentFormat=this._formats[i]||this.defaultTextFormat;currentFormat.updateContext(context);currentChar=this.text.charAt(i);textWidth=context.measureText(this.text.charAt(i)).width;
curLineHeight=context.measureText("M").width;lineHeight=curLineHeight>lineHeight?curLineHeight:lineHeight;if(x+textWidth>this.width||currentChar==TextField.NEW_LINE_CHARACTER){x=0;y+=lineHeight;lines.push(lineHeight);lineHeight=0;if(currentChar==TextField.NEW_LINE_CHARACTER){currentChar="";textWidth=0}}letterObj=new Letter;letterObj.value=currentChar;letterObj.index=i;letterObj.row=lines.length;letterObj.x=x;letterObj.y=0;letterObj.width=textWidth;letterObj.height=curLineHeight;letters.push(letterObj);
x+=textWidth;context.restore()}lines.push(curLineHeight>lineHeight?curLineHeight:lineHeight);i=0;max=letters.length;y=lines[0]+this.padding;currentRow=0;for(;i<max;i++){letterObj=letters[i];if(currentRow!=letterObj.row){currentRow=letterObj.row;y+=lines[currentRow]}letterObj.y=y}this._lineMetrics=lines;this._letters=letters;this._textHeight=y+this.padding};TextField.prototype.getLetters=function(context){return this._letters};
TextField.prototype._drawText=function(context){this._updateMetrics(context);var metrics=this._letters;var letterObj=null;var currentFormat=null;var i=0;var max=this._letters.length;var selected=false;for(i=0;i<max;i++){letterObj=metrics[i];context.save();currentFormat=this._formats[i]||this.defaultTextFormat;selected=i>=this._selectStart&&i<=this._selectEnd;if(selected==true){context.save();context.beginPath();context.fillStyle="black";context.fillRect(letterObj.x,letterObj.y-letterObj.height,letterObj.width,
letterObj.height);context.fill();context.restore()}currentFormat.updateContext(context);if(selected==true)context.globalCompositeOperation="xor";context.fillText(letterObj.value,letterObj.x,letterObj.y);context.restore()}};function TextFormat(){}TextFormat.prototype.textColor="black";TextFormat.prototype.textAlign="left";TextFormat.prototype.font="Arial";TextFormat.prototype.bold=false;TextFormat.prototype.italic=false;TextFormat.prototype.size=12;
TextFormat.prototype.updateContext=function(context){var bold=this.bold?"bold":"";var italic=this.italic?"italic":"";context.font=italic+" "+bold+" "+this.size+"px "+this.font;context.fillStyle=this.textColor;context.textAlign=this.textAlign};function Texture(){}Tomahawk.registerClass(Texture,"Texture");Texture.prototype.data=null;Texture.prototype.name=null;Texture.prototype.rect=null;function TextureAtlas(){this._textures=new Array}Tomahawk.registerClass(TextureAtlas,"TextureAtlas");
TextureAtlas.prototype._textures=null;TextureAtlas.prototype.data=null;TextureAtlas.prototype.name=null;TextureAtlas.prototype.createTexture=function(name,startX,startY,endX,endY){var texture=new Texture;texture.name=name;texture.data=this.data;texture.rect=[startX,startY,endX,endY];this._textures.push(texture)};TextureAtlas.prototype.getTextureByName=function(name){var i=this._textures.length;var currentTexture=null;while(--i>-1){currentTexture=this._textures[i];if(currentTexture.name==name)return currentTexture}return null};
TextureAtlas.prototype.removeTexture=function(name){var texture=this.getTextureByName(name);if(texture==null)return;var index=this._textures.indexOf(texture);this._textures.splice(index,1)};
